version: 1.0.{build}
image: Visual Studio 2017
before_build:
 - appveyor-retry dotnet restore -v Minimal
build:
  verbosity: minimal
on_success:
- curl -s -o upload https://test.duckbuild.io/ci/appveyor/scripts/upload
- bash upload
